# -------------------- Import Modules --------------------
from __future__ import annotations

import os
import time
from typing import Any, Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import BaggingClassifier, BaggingRegressor
from sklearn.tree import plot_tree

from Apollo.Backbone.Ensemble_BaseConfig import EnsembleBaseModelConfig, report_root


# -------------------- Bagging Missioner --------------------
class Bagging_Missioner(EnsembleBaseModelConfig):
    """
    Mission-layer base class for sklearn bagging ensemble workflows.

    This class centralizes shared logic for bagging-based ensemble models so
    that child model classes can focus on task-specific training, evaluation,
    and plotting behavior instead of repeatedly implementing the same bagging
    construction and prediction flow.

    The class supports both classification and regression bagging ensembles:

    - ``BaggingClassifier`` for classification tasks
    - ``BaggingRegressor`` for regression tasks

    Main responsibilities include:

    - validating the base estimator used in bagging
    - validating bagging sampling-related arguments
    - building the correct sklearn bagging estimator according to task type
    - fitting the bagging model through the inherited
      ``fit_with_grid(...)`` workflow
    - generating predictions from the fitted outer pipeline
    - generating probability predictions for classification tasks
    - retrieving the fitted final bagging estimator from the outer pipeline
    - providing shared feature-importance and tree-plot helpers for
      bagging models when supported

    Parameters
    ----------
    cleaned_X_data : pandas.DataFrame or None, optional
        Feature dataset passed from the inherited base configuration layer.

    cleaned_Y_data : pandas.Series, pandas.DataFrame, or None, optional
        Target dataset passed from the inherited base configuration layer.

    Attributes
    ----------
    task : str
        Task type defined by child classes. Expected values are
        ``"classification"`` or ``"regression"``.

    multioutput_scorer : Any
        Multi-output scoring configuration defined by child classes.

    input_model_type : str or None
        Name of the currently active bagging model type recorded during fitting.

    model_pipeline : sklearn.pipeline.Pipeline or None
        Final fitted outer pipeline created during training.

    prediction_preview : Any
        Cached preview of prediction output generated by ``predict_engine()``.

    feature_names : list[str] or None
        Feature names captured from the fitted pipeline.

    Notes
    -----
    This is a mission-layer helper base class and is not usually intended to be
    instantiated directly. Child classes are expected to define the correct
    ``task`` value and provide task-specific training and evaluation methods.

    This class supports two preprocessing styles:

    1. outer preprocessing via ``fit_with_grid(use_preprocess=True)``
    2. estimator-owned pipelines via ``fit_with_grid(use_preprocess=False)``

    In bagging workflows, a single base estimator is repeatedly trained on
    different bootstrap samples and, optionally, different feature subsets.

    Typical child classes include:

    - ``BaggingClassifier_Model``
    - ``BaggingRegressor_Model``
    """

    # -------------------- Validation for estimator --------------------
    def _validate_estimator(
        self,
        estimator: Any,
    ):
        """
        Validate the base estimator used in a bagging workflow.

        This helper checks whether a valid estimator object has been provided
        for bagging construction.

        Parameters
        ----------
        estimator : Any
            sklearn-compatible estimator or pipeline used as the bagging
            base learner.

        Returns
        -------
        Any
            The validated estimator object.

        Raises
        ------
        ValueError
            If ``estimator`` is ``None``.

        Notes
        -----
        This helper only checks that an estimator object exists. It does not
        verify whether the estimator is compatible with the selected task type;
        sklearn will enforce deeper compatibility during fitting.
        """
        if estimator is None:
            raise ValueError("⚠️ estimator cannot be None ‼️")
        return estimator

    # -------------------- Validation for bagging sample settings --------------------
    def _validate_sampling_args(
        self,
        n_estimators: int,
        max_samples: float | int = 1.0,
        max_features: float | int = 1.0,
    ):
        """
        Validate bagging sampling-related configuration.

        This helper checks whether the ensemble size and sampling arguments are
        structurally valid before constructing a bagging estimator.

        Parameters
        ----------
        n_estimators : int
            Number of base estimators in the bagging ensemble.

        max_samples : float or int, default=1.0
            Number or fraction of training samples drawn for each base
            estimator.

            - If ``int``, the value must be at least ``1``.
            - If ``float``, the value must be in the interval ``(0, 1]``.

        max_features : float or int, default=1.0
            Number or fraction of input features drawn for each base estimator.

            - If ``int``, the value must be at least ``1``.
            - If ``float``, the value must be in the interval ``(0, 1]``.

        Returns
        -------
        None

        Raises
        ------
        ValueError
            If ``n_estimators`` is not an integer greater than or equal to 1.

        ValueError
            If ``max_samples`` is neither a valid integer count nor a valid
            float fraction.

        ValueError
            If ``max_features`` is neither a valid integer count nor a valid
            float fraction.

        Notes
        -----
        This helper validates basic parameter ranges only. It does not compare
        the values against the actual dataset size or feature count at this
        stage.
        """
        if not isinstance(n_estimators, int) or n_estimators < 1:
            raise ValueError("⚠️ n_estimators must be an integer >= 1 ‼️")

        if isinstance(max_samples, int):
            if max_samples < 1:
                raise ValueError("⚠️ int max_samples must be >= 1 ‼️")
        elif isinstance(max_samples, float):
            if not (0 < max_samples <= 1):
                raise ValueError("⚠️ float max_samples must be in (0, 1] ‼️")
        else:
            raise ValueError("⚠️ max_samples must be int or float ‼️")

        if isinstance(max_features, int):
            if max_features < 1:
                raise ValueError("⚠️ int max_features must be >= 1 ‼️")
        elif isinstance(max_features, float):
            if not (0 < max_features <= 1):
                raise ValueError("⚠️ float max_features must be in (0, 1] ‼️")
        else:
            raise ValueError("⚠️ max_features must be int or float ‼️")

    # -------------------- Build bagging estimator --------------------
    def _build_bagging_model(
        self,
        estimator: Any,
        n_estimators: int = 10,
        max_samples: float | int = 1.0,
        max_features: float | int = 1.0,
        bootstrap: bool = True,
        bootstrap_features: bool = False,
        oob_score: bool = False,
        warm_start: bool = False,
        n_jobs: Optional[int] = -1,
        random_state: int = 42,
    ):
        """
        Build a sklearn bagging ensemble estimator according to the current task.

        This method validates the base estimator and bagging sampling arguments,
        then constructs either a ``BaggingClassifier`` or ``BaggingRegressor``
        depending on ``self.task``.

        Parameters
        ----------
        estimator : Any
            Base estimator used in the bagging ensemble.

        n_estimators : int, default=10
            Number of base estimators in the ensemble.

        max_samples : float or int, default=1.0
            Number or fraction of samples drawn to train each base estimator.

        max_features : float or int, default=1.0
            Number or fraction of features drawn to train each base estimator.

        bootstrap : bool, default=True
            Whether training samples are drawn with replacement.

        bootstrap_features : bool, default=False
            Whether features are drawn with replacement.

        oob_score : bool, default=False
            Whether to compute out-of-bag generalization score.

        warm_start : bool, default=False
            Whether to reuse the previous fitted solution and add more
            estimators across repeated ``fit()`` calls.

        n_jobs : int or None, default=-1
            Number of parallel jobs used by the sklearn bagging estimator.

        random_state : int, default=42
            Random seed used for bagging reproducibility.

        Returns
        -------
        sklearn.ensemble.BaggingClassifier or sklearn.ensemble.BaggingRegressor
            A constructed sklearn bagging ensemble estimator matching the
            current task type.

        Raises
        ------
        ValueError
            If ``self.task`` is not ``"classification"`` or ``"regression"``.

        Notes
        -----
        This method only builds the sklearn bagging estimator object. Model
        fitting is handled separately by ``bagging_fit_engine()`` through the
        inherited ``fit_with_grid(...)`` workflow.
        """
        checked_estimator = self._validate_estimator(estimator)
        self._validate_sampling_args(
            n_estimators=n_estimators,
            max_samples=max_samples,
            max_features=max_features,
        )

        if self.task == "classification":
            model = BaggingClassifier(
                estimator=checked_estimator,
                n_estimators=n_estimators,
                max_samples=max_samples,
                max_features=max_features,
                bootstrap=bootstrap,
                bootstrap_features=bootstrap_features,
                oob_score=oob_score,
                warm_start=warm_start,
                n_jobs=n_jobs,
                random_state=random_state,
            )
            return model

        if self.task == "regression":
            model = BaggingRegressor(
                estimator=checked_estimator,
                n_estimators=n_estimators,
                max_samples=max_samples,
                max_features=max_features,
                bootstrap=bootstrap,
                bootstrap_features=bootstrap_features,
                oob_score=oob_score,
                warm_start=warm_start,
                n_jobs=n_jobs,
                random_state=random_state,
            )
            return model

        raise ValueError("⚠️ task must be 'classification' or 'regression' ‼️")

    # -------------------- Bagging fit engine --------------------
    def bagging_fit_engine(
        self,
        estimator: Any,
        n_estimators: int = 10,
        use_cv: bool = False,
        cv_folds: int = 5,
        scoring: str = "f1_weighted",
        max_samples: float | int = 1.0,
        max_features: float | int = 1.0,
        bootstrap: bool = True,
        bootstrap_features: bool = False,
        oob_score: bool = False,
        warm_start: bool = False,
        n_jobs: Optional[int] = -1,
        param_grid: Optional[Dict[str, Any]] = None,
        random_state: int = 42,
        extra_steps: Optional[List[Tuple[str, Any]]] = None,
        use_preprocess: bool = True,
        categorical_cols: Optional[List[str]] = None,
        numeric_cols: Optional[List[str]] = None,
        cat_encoder: str = "ohe",
    ) -> Dict[str, Any]:
        """
        Build and fit a bagging ensemble model through the shared training pipeline.

        This method constructs the underlying bagging estimator, sends it into
        the inherited ``fit_with_grid(...)`` workflow, and returns a compact
        summary dictionary describing the bagging training run.

        Depending on configuration, training can be performed in two modes:

        - direct fit without cross-validation
        - grid-search fit using ``GridSearchCV``

        Outer preprocessing can also be enabled or disabled depending on
        whether preprocessing is handled by the shared outer pipeline or
        already built into the inner estimator.

        Parameters
        ----------
        estimator : Any
            Base estimator used in bagging.

        n_estimators : int, default=10
            Number of base estimators in the bagging ensemble.

        use_cv : bool, default=False
            Whether to perform hyperparameter search with ``GridSearchCV``.

        cv_folds : int, default=5
            Number of folds used when ``use_cv=True``.

        scoring : str, default="f1_weighted"
            sklearn scoring string used for single-output model selection.

            Common examples include:

            Classification:
            - ``"accuracy"``
            - ``"f1"``
            - ``"f1_weighted"``
            - ``"roc_auc"``

            Regression:
            - ``"r2"``
            - ``"neg_mean_squared_error"``
            - ``"neg_mean_absolute_error"``

        max_samples : float or int, default=1.0
            Number or fraction of samples drawn for each base estimator.

        max_features : float or int, default=1.0
            Number or fraction of features drawn for each base estimator.

        bootstrap : bool, default=True
            Whether rows are sampled with replacement.

        bootstrap_features : bool, default=False
            Whether columns are sampled with replacement.

        oob_score : bool, default=False
            Whether out-of-bag evaluation should be enabled.

        warm_start : bool, default=False
            Whether the ensemble should reuse its previous fitted state when
            fitting repeatedly.

        n_jobs : int or None, default=-1
            Number of parallel jobs used by the bagging estimator.

        param_grid : dict[str, Any] or None, default=None
            Parameter grid passed to ``fit_with_grid(...)`` for cross-validation.

            Parameter names should use the outer pipeline step prefix.

            Examples
            --------
            Classification::

                {
                    "classifier__n_estimators": [10, 50, 100],
                    "classifier__max_samples": [0.7, 1.0],
                }

            Regression::

                {
                    "regressor__n_estimators": [10, 50, 100],
                    "regressor__max_features": [0.5, 1.0],
                }

        random_state : int, default=42
            Random seed forwarded to both the bagging estimator and CV splitter
            construction.

        extra_steps : list[tuple[str, Any]] or None, default=None
            Optional pipeline steps inserted between preprocessing and the final
            bagging estimator.

        use_preprocess : bool, default=True
            Whether to include outer preprocessing in the training pipeline.

        categorical_cols : list[str] or None, default=None
            Categorical feature columns passed to the outer preprocessing
            builder when ``use_preprocess=True``.

        numeric_cols : list[str] or None, default=None
            Numeric feature columns passed to the outer preprocessing builder
            when ``use_preprocess=True``.

        cat_encoder : str, default="ohe"
            Categorical encoder type passed to the outer preprocessing builder
            when ``use_preprocess=True``.

        Returns
        -------
        dict[str, Any]
            A compact training summary dictionary containing information such as:

            - input model type
            - task type
            - base estimator type
            - ensemble size
            - sampling settings
            - bootstrap settings
            - out-of-bag usage
            - warm-start usage
            - CV usage
            - CV folds
            - scoring method
            - preprocessing usage
            - best parameters
            - best score
            - feature names

        Notes
        -----
        The fitted pipeline itself is stored internally in ``self.model_pipeline``
        by the inherited training workflow.

        The returned dictionary is intended as a compact run summary and is not
        a replacement for the fitted outer pipeline object.
        """
        self.input_model_type = (
            "BaggingClassifier" if self.task == "classification" else "BaggingRegressor"
        )

        bagging_model = self._build_bagging_model(
            estimator=estimator,
            n_estimators=n_estimators,
            max_samples=max_samples,
            max_features=max_features,
            bootstrap=bootstrap,
            bootstrap_features=bootstrap_features,
            oob_score=oob_score,
            warm_start=warm_start,
            n_jobs=n_jobs,
            random_state=random_state,
        )

        best_params, best_score = self.fit_with_grid(
            base_model=bagging_model,
            param_grid=param_grid,
            use_cv=use_cv,
            cv_folds=cv_folds,
            scoring=scoring,
            random_state=random_state,
            extra_steps=extra_steps,
            use_preprocess=use_preprocess,
            categorical_cols=categorical_cols,
            numeric_cols=numeric_cols,
            cat_encoder=cat_encoder,
        )

        return {
            "input_model_type": self.input_model_type,
            "task": self.task,
            "base_estimator": type(estimator).__name__,
            "n_estimators": n_estimators,
            "max_samples": max_samples,
            "max_features": max_features,
            "bootstrap": bootstrap,
            "bootstrap_features": bootstrap_features,
            "oob_score_enabled": oob_score,
            "warm_start": warm_start,
            "use_cv": use_cv,
            "cv_folds": cv_folds if use_cv else None,
            "scoring": scoring,
            "use_preprocess": use_preprocess,
            "best_params": best_params,
            "best_score": best_score,
            "feature_names": self.feature_names,
        }

    # -------------------- Predict --------------------
    def predict_engine(
        self,
        X_data: Optional[pd.DataFrame] = None,
        preview: int = 5,
    ):
        """
        Generate predictions using the fitted bagging pipeline.

        This method calls ``predict()`` on the internally stored fitted outer
        pipeline. If no input data is provided, it falls back to ``self.X_test``.

        A short prediction preview is also cached into
        ``self.prediction_preview`` for later inspection.

        Parameters
        ----------
        X_data : pandas.DataFrame or None, default=None
            Input feature data for prediction. If ``None``, the method attempts
            to use ``self.X_test``.

        preview : int, default=5
            Number of predicted rows stored in ``self.prediction_preview``.

        Returns
        -------
        Any
            Prediction output returned by the fitted pipeline.

            - For regression tasks, this is typically an array-like collection of
            predicted numeric values.
            - For classification tasks, predictions are returned after optional
            target-label decoding. If target label encoding was applied during
            training, the returned values are typically the original class labels
            rather than encoded class indices.

            In multi-output classification workflows, the returned object may be a
            pandas DataFrame containing decoded target columns.

        Raises
        ------
        ValueError
            If the model pipeline has not been fitted yet.

        ValueError
            If ``X_data`` is ``None`` and ``self.X_test`` is also unavailable.

        Notes
        -----
        This method stores a small preview of predictions in ``self.prediction_preview``
        when possible, which can be useful for quick inspection, logging, or debugging.

        If target-side label encoding was applied during training, predictions are
        passed through ``self._maybe_decode_predictions(...)`` before preview caching
        and return.
        """
        if self.model_pipeline is None:
            raise ValueError("⚠️ Train the model before prediction ‼️")

        if X_data is None:
            if self.X_test is None:
                raise ValueError("⚠️ No X_data provided and X_test is unavailable ‼️")
            X_data = self.X_test

        preds = self.model_pipeline.predict(X_data)
        preds = self._maybe_decode_predictions(preds)

        try:
            self.prediction_preview = preds[:preview]
        except Exception:
            self.prediction_preview = preds

        return preds

    # -------------------- Predict probability --------------------
    def predict_proba_engine(
        self,
        X_data: Optional[pd.DataFrame] = None,
    ):
        """
        Predict class probabilities using the fitted bagging classification pipeline.

        This method is only valid for classification tasks. It calls
        ``predict_proba()`` on the internally stored fitted outer pipeline.

        If no input data is provided, the method falls back to ``self.X_test``.

        Parameters
        ----------
        X_data : pandas.DataFrame or None, default=None
            Input feature data for probability prediction. If ``None``, the
            method attempts to use ``self.X_test``.

        Returns
        -------
        Any
            Probability prediction output returned by ``predict_proba()``.
            This is typically a NumPy array of class probabilities.

        Raises
        ------
        ValueError
            If the current task is not classification.

        ValueError
            If the model pipeline has not been fitted yet.

        ValueError
            If ``X_data`` is ``None`` and ``self.X_test`` is also unavailable.

        AttributeError
            If the fitted pipeline does not support ``predict_proba()``.

        Notes
        -----
        This method requires that the final fitted bagging workflow exposes
        ``predict_proba()``. In practice, that usually means the fitted model
        is a ``BaggingClassifier`` built on a probability-capable base estimator.
        """
        if self.task != "classification":
            raise ValueError("⚠️ predict_proba_engine() is only for classification ‼️")

        if self.model_pipeline is None:
            raise ValueError("⚠️ Train the model before predict_proba ‼️")

        if X_data is None:
            if self.X_test is None:
                raise ValueError("⚠️ No X_data provided and X_test is unavailable ‼️")
            X_data = self.X_test

        if not hasattr(self.model_pipeline, "predict_proba"):
            raise AttributeError(
                "⚠️ This fitted bagging pipeline does not support predict_proba ‼️"
            )

        return self.model_pipeline.predict_proba(X_data)

    # -------------------- Fitted bagging estimator getter --------------------
    def get_fitted_bagging_estimator(self):
        """
        Return the fitted final bagging estimator from the outer pipeline.

        This method retrieves the final bagging estimator step stored inside
        ``self.model_pipeline.named_steps`` using ``self.step_name``.

        It is useful when direct access to the fitted sklearn
        ``BaggingClassifier`` or ``BaggingRegressor`` object is needed after
        the outer pipeline has already been built and fitted.

        Returns
        -------
        Any
            The fitted final bagging estimator stored in the pipeline.
            This is typically a ``BaggingClassifier`` or ``BaggingRegressor``.

        Raises
        ------
        ValueError
            If ``self.model_pipeline`` is not fitted or unavailable.

        KeyError
            If the expected final estimator step name does not exist in
            ``self.model_pipeline.named_steps``.

        Notes
        -----
        This method returns only the final bagging estimator, not the full
        preprocessing-plus-model pipeline. Use ``self.model_pipeline`` directly
        when access to the full outer pipeline is needed.
        """
        if self.model_pipeline is None:
            raise ValueError("⚠️ model_pipeline is not fitted yet ‼️")

        if self.step_name not in self.model_pipeline.named_steps:
            raise KeyError(f"⚠️ Step '{self.step_name}' not found in model_pipeline ‼️")

        return self.model_pipeline.named_steps[self.step_name]

    # -------------------- Feature importance plot --------------------
    def feature_importance_engine(
        self,
        max_display: int = 20,
        save_fig: bool = False,
        folder_name: str = "Feature_Importance",
        file_name: str | None = None,
    ):
        """
        Compute and display feature importance for a fitted bagging estimator.

        This method retrieves the fitted bagging estimator and attempts to build
        full-length feature-importance vectors aligned with the final feature
        space.

        Two main cases are supported:

        1. the fitted bagging estimator itself exposes ``feature_importances_``
        2. the fitted bagging estimator exposes ``estimators_`` and feature
           importances must be aggregated across base estimators

        When aggregation is required, the method uses
        ``estimators_features_`` when available to map per-estimator local
        importances back to the full feature space.

        The method then builds a pandas DataFrame, plots the top features as a
        horizontal bar chart, optionally saves the figure, and returns the full
        importance table.

        Parameters
        ----------
        max_display : int, default=20
            Maximum number of top-ranked features displayed in the plot.

        save_fig : bool, default=False
            Whether to save the generated figure to disk.

        folder_name : str, default="Feature_Importance"
            Folder created under ``report_root`` when saving the figure.

        file_name : str or None, optional
            Custom output filename for the saved figure. If ``None``, an
            automatic timestamp-based filename is generated.

        Returns
        -------
        pandas.DataFrame
            Feature-importance table containing:

            - ``feature``
            - ``importance_mean``
            - ``importance_std``

            The table is sorted by descending mean importance.

        Raises
        ------
        ValueError
            If no fitted bagging estimator is available.

        ValueError
            If feature-importance values cannot be aligned to the full feature
            space.

        ValueError
            If the current fitted bagging estimator does not support feature
            importance extraction.

        Notes
        -----
        For bagging models, feature importance may require aggregation over
        individual base estimators rather than reading a single
        ``feature_importances_`` vector from the ensemble itself.

        The returned DataFrame contains the full feature table, while the plot
        only shows the top ``max_display`` entries.
        """
        fitted_model = self.get_fitted_bagging_estimator()

        if fitted_model is None:
            raise ValueError("⚠️ No fitted Bagging estimator available ‼️")

        feature_names = (
            self.feature_names
            if self.feature_names is not None
            else self.cleaned_X_data.columns.tolist()
        )
        n_features = len(feature_names)

        full_importances = []

        # ---------- Case 1: bagging model itself exposes feature_importances_ ----------
        if hasattr(fitted_model, "feature_importances_"):
            importances = fitted_model.feature_importances_

            if len(importances) != n_features:
                raise ValueError(
                    f"⚠️ feature_importances_ length mismatch: "
                    f"{len(importances)} vs feature_names {n_features} ‼️"
                )

            importance_mean = np.asarray(importances, dtype=float)
            importance_std = np.zeros_like(importance_mean, dtype=float)

        # ---------- Case 2: aggregate sub-estimators ----------
        elif hasattr(fitted_model, "estimators_"):
            estimators = fitted_model.estimators_

            # sklearn bagging usually stores per-estimator selected feature indices here
            estimators_features = getattr(fitted_model, "estimators_features_", None)

            for idx, est in enumerate(estimators):
                if not hasattr(est, "feature_importances_"):
                    continue

                local_imp = np.asarray(est.feature_importances_, dtype=float)
                full_imp = np.zeros(n_features, dtype=float)

                if estimators_features is not None:
                    feat_idx = np.asarray(estimators_features[idx])

                    if len(local_imp) != len(feat_idx):
                        raise ValueError(
                            f"⚠️ estimator {idx} importance length "
                            f"{len(local_imp)} does not match selected feature count "
                            f"{len(feat_idx)} ‼️"
                        )

                    full_imp[feat_idx] = local_imp

                else:
                    # fallback: only safe when local importance length already matches full feature count
                    if len(local_imp) != n_features:
                        raise ValueError(
                            "⚠️ Cannot align Bagging feature importances because "
                            "estimators_features_ is unavailable and local importance "
                            "length does not match full feature count ‼️"
                        )
                    full_imp = local_imp

                full_importances.append(full_imp)

            if not full_importances:
                raise ValueError(
                    "⚠️ Current Bagging estimator does not support feature importance ‼️"
                )

            full_importances = np.vstack(full_importances)
            importance_mean = np.mean(full_importances, axis=0)
            importance_std = np.std(full_importances, axis=0)

        else:
            raise ValueError(
                "⚠️ Current Bagging estimator does not support feature importance ‼️"
            )

        importance_df = pd.DataFrame(
            {
                "feature": feature_names,
                "importance_mean": importance_mean,
                "importance_std": importance_std,
            }
        ).sort_values("importance_mean", ascending=False)

        display_df = importance_df.head(max_display).iloc[::-1]

        plt.figure(figsize=(10, max(5, len(display_df) * 0.35)))
        plt.barh(display_df["feature"], display_df["importance_mean"])
        plt.xlabel("Feature Importance")
        plt.ylabel("Feature")
        plt.title(f"{self.__class__.__name__} Feature Importance")
        plt.tight_layout()

        if save_fig:
            save_folder = os.path.join(report_root, folder_name)
            os.makedirs(save_folder, exist_ok=True)

            if file_name is None:
                timestamp = time.strftime("%Y%m%d_%H%M%S")
                file_name = (
                    f"{self.__class__.__name__}_feature_importance_{timestamp}.png"
                )

            save_path = os.path.join(save_folder, file_name)
            plt.savefig(save_path, dpi=200, bbox_inches="tight")
            print(f"🔥 Feature importance figure saved: {save_path}")

        plt.show()
        return importance_df

    # -------------------- Tree Plot --------------------
    def tree_plot_engine(
        self,
        tree_indices: int | list[int] | tuple[int, ...] = 0,
        max_depth: int | None = 3,
        save_fig: bool = False,
        folder_name: str = "Tree_Plot",
        file_name: str | None = None,
    ):
        """
        Plot one or more fitted tree-based estimators from a bagging ensemble.

        This method retrieves the fitted final bagging estimator from the outer
        pipeline, validates the requested tree indices, and visualizes the selected
        base estimators one by one using ``sklearn.tree.plot_tree``.

        The method supports both a single integer index and multiple indices. When
        multiple indices are provided, each selected tree is plotted in sequence as
        an individual figure.

        Parameters
        ----------
        tree_indices : int or list[int] or tuple[int, ...], default=0
            Index or collection of indices identifying which fitted base estimators
            inside the bagging ensemble should be plotted.

            Examples:
            - ``0`` for a single tree
            - ``[0, 2, 4]`` for multiple trees
            - ``(1, 3, 5)`` for multiple trees

        max_depth : int or None, default=3
            Maximum tree depth shown in the plotted visualization.

            - If an integer is provided, the displayed tree is truncated to that depth.
            - If ``None``, the full tree structure is displayed.

        save_fig : bool, default=False
            Whether each plotted tree figure should also be saved to disk.

        folder_name : str, default="Tree_Plot"
            Folder name created under ``report_root`` when ``save_fig=True``.

        file_name : str or None, default=None
            Optional custom output filename prefix used when saving figures.

            - If ``None``, each saved figure receives an automatically generated
            filename based on the class name, tree index, and timestamp.
            - If provided, the tree index is appended so that multiple selected
            trees are saved as separate files.

        Returns
        -------
        None
            The method displays one or more matplotlib figures and optionally saves
            them to disk.

        Raises
        ------
        ValueError
            If no fitted bagging estimator is available.

        ValueError
            If the fitted bagging estimator does not expose ``estimators_``.

        ValueError
            If ``tree_indices`` is empty after normalization.

        ValueError
            If any requested tree index is outside the valid range.

        ValueError
            If any selected base estimator is not tree-based and therefore does not
            expose a ``tree_`` attribute.

        Notes
        -----
        - This method is intended for bagging ensembles whose base estimators are
        tree models or pipelines ending in tree models.
        - Each selected tree is plotted as a separate figure rather than combined
        into subplots.
        - When ``save_fig=True``, files are saved under
        ``os.path.join(report_root, folder_name)``.
        - The figure title includes both the class name and the selected
        ``tree_index``.
        - Figures are closed with ``plt.close()`` after display to reduce plot
        accumulation during repeated interactive use.
        """
        fitted_model = self.get_fitted_bagging_estimator()

        if fitted_model is None:
            raise ValueError("⚠️ No fitted Bagging estimator available ‼️")

        if not hasattr(fitted_model, "estimators_"):
            raise ValueError(
                "⚠️ Current Bagging estimator does not expose estimators_ ‼️"
            )

        if isinstance(tree_indices, int):
            tree_indices = [tree_indices]
        else:
            tree_indices = list(tree_indices)

        if not tree_indices:
            raise ValueError("⚠️ tree_indices cannot be empty ‼️")

        total_trees = len(fitted_model.estimators_)

        for idx in tree_indices:
            if idx < 0 or idx >= total_trees:
                raise ValueError(
                    f"⚠️ tree_index {idx} is out of range (0 ~ {total_trees - 1}) ‼️"
                )

            tree_model = fitted_model.estimators_[idx]

            if not hasattr(tree_model, "tree_"):
                raise ValueError(
                    f"⚠️ Selected base estimator {idx} is not tree-based ‼️"
                )

            plt.figure(figsize=(18, 10))
            plot_tree(
                tree_model,
                feature_names=self.feature_names,
                filled=True,
                max_depth=max_depth,
                fontsize=8,
            )
            plt.title(f"{self.__class__.__name__} Tree Plot (tree_index={idx})")
            plt.tight_layout()

            if save_fig:
                save_folder = os.path.join(report_root, folder_name)
                os.makedirs(save_folder, exist_ok=True)

                timestamp = time.strftime("%Y%m%d_%H%M%S")
                if file_name is None:
                    out_name = f"{self.__class__.__name__}_tree_{idx}_{timestamp}.png"
                else:
                    stem, ext = os.path.splitext(file_name)
                    ext = ext or ".png"
                    out_name = f"{stem}_tree_{idx}{ext}"

                save_path = os.path.join(save_folder, out_name)
                plt.savefig(save_path, dpi=200, bbox_inches="tight")
                print(f"🔥 Tree plot figure saved: {save_path}")

            plt.show()
            plt.close()


# =================================================
