# -------------------- Import Modules --------------------
from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence, Tuple

import pandas as pd
from sklearn.ensemble import StackingClassifier, StackingRegressor

from Apollo.Backbone.Ensemble_BaseConfig import EnsembleBaseModelConfig


# -------------------- Stacking Missioner --------------------
class Stacking_Missioner(EnsembleBaseModelConfig):
    """
    Mission-layer base class for stacking ensemble workflows.

    This class centralizes shared logic for sklearn stacking models so that
    child model classes can focus on task-specific responsibilities such as
    task declaration, evaluation logic, and custom scoring behavior.

    The class supports both classification and regression stacking ensembles:

    - ``StackingClassifier`` for classification tasks
    - ``StackingRegressor`` for regression tasks

    Main responsibilities include:

    - validating the first-layer estimator collection
    - validating the final meta-estimator
    - validating classification stack-method configuration
    - building the correct sklearn stacking estimator according to task type
    - fitting the stacking model through the inherited
      ``fit_with_grid(...)`` workflow
    - generating predictions from the fitted outer pipeline
    - generating class probabilities for classification tasks
    - retrieving the fitted final stacking estimator from the outer pipeline
    - returning a compact training summary dictionary

    Parameters
    ----------
    cleaned_X_data : pandas.DataFrame or None, optional
        Feature dataset passed from the inherited base configuration layer.

    cleaned_Y_data : pandas.Series, pandas.DataFrame, or None, optional
        Target dataset passed from the inherited base configuration layer.

    Attributes
    ----------
    task : str
        Task type defined by child classes. Expected values are
        ``"classification"`` or ``"regression"``.

    multioutput_scorer : Any
        Multi-output scoring configuration defined by child classes.

    input_model_type : str or None
        Name of the currently active stacking model type recorded during fitting.

    model_pipeline : sklearn.pipeline.Pipeline or None
        Final fitted outer pipeline created during training.

    prediction_preview : Any
        Cached preview of prediction output generated by ``predict_engine()``.

    feature_names : list[str] or None
        Feature names captured from the fitted pipeline.

    Notes
    -----
    This is a mission-layer helper base class and is not usually intended to be
    instantiated directly. Child classes are expected to define the correct
    ``task`` value and provide task-specific training and evaluation methods.

    Stacking is a layered ensemble method that combines multiple first-layer
    estimators with one final meta-estimator. The first-layer estimators
    produce outputs that are used as meta-features for the final estimator.

    This class supports two preprocessing styles:

    1. outer preprocessing via ``fit_with_grid(use_preprocess=True)``
    2. estimator-owned pipelines via ``fit_with_grid(use_preprocess=False)``

    Typical child classes include:

    - ``StackingClassifier_Model``
    - ``StackingRegressor_Model``
    """

    # -------------------- Validation for final estimator --------------------
    def _validate_final_estimator(
        self,
        final_estimator: Any,
    ):
        """
        Validate the final meta-estimator used in a stacking workflow.

        This helper checks whether a final estimator object has been provided
        for the stacking ensemble.

        Parameters
        ----------
        final_estimator : Any
            sklearn-compatible estimator or pipeline used as the final
            meta-estimator.

            This estimator receives the meta-features produced by the
            first-layer estimators and learns how to combine them into the
            final prediction.

        Returns
        -------
        Any
            The validated final estimator object.

        Raises
        ------
        ValueError
            If ``final_estimator`` is ``None``.

        Notes
        -----
        This helper only checks that a final estimator object exists. It does
        not perform deep compatibility validation for task type or estimator
        capabilities.
        """
        if final_estimator is None:
            raise ValueError("⚠️ final_estimator cannot be None ‼️")
        return final_estimator

    # -------------------- Validation for stack_method --------------------
    def _validate_stack_method(
        self,
        stack_method: str = "auto",
    ):
        """
        Validate the stack-method configuration for classification stacking.

        This helper normalizes the input string and checks whether it is a
        supported sklearn stack-method option for ``StackingClassifier``.

        Parameters
        ----------
        stack_method : str, default="auto"
            Method used to generate first-layer outputs for meta-learning in
            classification workflows.

            Supported values are:

            - ``"auto"``
            - ``"predict_proba"``
            - ``"decision_function"``
            - ``"predict"``

        Returns
        -------
        None

        Raises
        ------
        ValueError
            If ``stack_method`` is not one of the supported options.

        Notes
        -----
        This validation applies only to classification workflows.
        Regression stacking does not use ``stack_method``.
        """
        stack_method = stack_method.lower().strip()
        if stack_method not in {
            "auto",
            "predict_proba",
            "decision_function",
            "predict",
        }:
            raise ValueError(
                "⚠️ stack_method must be 'auto', 'predict_proba', "
                "'decision_function', or 'predict' ‼️"
            )

    # -------------------- Build stacking estimator --------------------
    def _build_stacking_model(
        self,
        estimators: Sequence[Tuple[str, Any]],
        final_estimator: Any,
        cv: int = 5,
        n_jobs: Optional[int] = -1,
        passthrough: bool = False,
        stack_method: str = "auto",
    ):
        """
        Build a sklearn stacking estimator according to the current task type.

        This method validates the first-layer estimators, validates the final
        meta-estimator, and constructs either a ``StackingClassifier`` or
        ``StackingRegressor`` depending on ``self.task``.

        Parameters
        ----------
        estimators : Sequence[Tuple[str, Any]]
            Sequence of first-layer estimator-name and estimator-object pairs,
            for example::

                [
                    ("knn", knn_model),
                    ("svc", svc_model),
                    ("rf", rf_model),
                ]

            At least two estimators are typically required for a meaningful
            stacking workflow.

        final_estimator : Any
            Final meta-estimator trained on the meta-features generated by the
            first-layer estimators.

        cv : int, default=5
            Number of internal cross-validation folds used by sklearn stacking
            to generate out-of-fold predictions for training the final
            estimator.

        n_jobs : int or None, default=-1
            Number of parallel jobs used where supported by the sklearn
            stacking estimator.

        passthrough : bool, default=False
            Whether original input features are concatenated with first-layer
            outputs before fitting the final meta-estimator.

        stack_method : str, default="auto"
            Classification-only setting controlling which first-layer outputs
            are used for meta-learning.

        Returns
        -------
        sklearn.ensemble.StackingClassifier or sklearn.ensemble.StackingRegressor
            A constructed sklearn stacking model matching the current task type.

        Raises
        ------
        ValueError
            If the estimator collection is invalid.

        ValueError
            If the final estimator is invalid.

        ValueError
            If ``stack_method`` is invalid for classification.

        ValueError
            If ``self.task`` is not ``"classification"`` or ``"regression"``.

        Notes
        -----
        This method only builds the sklearn stacking estimator object.
        Model fitting is handled separately by ``stacking_fit_engine()``.
        """
        checked_estimators = self._validate_estimators(
            estimators=estimators,
            min_estimators=2,
        )
        checked_final_estimator = self._validate_final_estimator(final_estimator)

        if self.task == "classification":
            self._validate_stack_method(stack_method)
            model = StackingClassifier(
                estimators=checked_estimators,
                final_estimator=checked_final_estimator,
                cv=cv,
                n_jobs=n_jobs,
                passthrough=passthrough,
                stack_method=stack_method,
            )
            return model

        if self.task == "regression":
            model = StackingRegressor(
                estimators=checked_estimators,
                final_estimator=checked_final_estimator,
                cv=cv,
                n_jobs=n_jobs,
                passthrough=passthrough,
            )
            return model

        raise ValueError("⚠️ task must be 'classification' or 'regression' ‼️")

    # -------------------- Stacking fit engine --------------------
    def stacking_fit_engine(
        self,
        estimators: Sequence[Tuple[str, Any]],
        final_estimator: Any,
        use_cv: bool = False,
        cv_folds: int = 5,
        scoring: str = "f1_weighted",
        stacking_cv: int = 5,
        n_jobs: Optional[int] = -1,
        passthrough: bool = False,
        stack_method: str = "auto",
        param_grid: Optional[Dict[str, Any]] = None,
        random_state: int = 42,
        extra_steps: Optional[List[Tuple[str, Any]]] = None,
        use_preprocess: bool = True,
        categorical_cols: Optional[List[str]] = None,
        numeric_cols: Optional[List[str]] = None,
        cat_encoder: str = "ohe",
    ) -> Dict[str, Any]:
        """
        Build and fit a stacking ensemble model through the shared training pipeline.

        This method constructs the underlying stacking estimator, sends it into
        the inherited ``fit_with_grid(...)`` workflow, and returns a compact
        summary dictionary describing the stacking training run.

        Parameters
        ----------
        estimators : Sequence[Tuple[str, Any]]
            First-layer estimator collection used to generate meta-features.

        final_estimator : Any
            Final meta-estimator trained on the outputs of the first-layer
            estimators.

        use_cv : bool, default=False
            Whether to perform hyperparameter search with ``GridSearchCV`` on
            the outer pipeline.

        cv_folds : int, default=5
            Number of folds used when ``use_cv=True``.

        scoring : str, default="f1_weighted"
            sklearn scoring string used for single-output model selection.

        stacking_cv : int, default=5
            Number of internal cross-validation folds used by the sklearn
            stacking estimator to create out-of-fold meta-features.

        n_jobs : int or None, default=-1
            Number of parallel jobs used where supported by the stacking
            estimator.

        passthrough : bool, default=False
            Whether original input features are concatenated with first-layer
            outputs before fitting the final meta-estimator.

        stack_method : str, default="auto"
            Classification-only setting controlling which first-layer outputs
            are used for meta-learning.

        param_grid : dict[str, Any] or None, default=None
            Parameter grid passed to ``fit_with_grid(...)`` for cross-validation.

            Parameter names should use the outer pipeline step prefix.

            Examples
            --------
            Classification::

                {
                    "classifier__passthrough": [False, True],
                    "classifier__final_estimator__C": [0.1, 1.0, 10.0],
                }

            Regression::

                {
                    "regressor__passthrough": [False, True],
                    "regressor__final_estimator__alpha": [0.1, 1.0],
                }

        random_state : int, default=42
            Random seed forwarded to the inherited outer CV splitter
            construction.

        extra_steps : list[tuple[str, Any]] or None, default=None
            Optional pipeline steps inserted between preprocessing and the final
            stacking estimator.

        use_preprocess : bool, default=True
            Whether to include outer preprocessing in the training pipeline.

        categorical_cols : list[str] or None, default=None
            Categorical feature columns passed to the outer preprocessing
            builder when ``use_preprocess=True``.

        numeric_cols : list[str] or None, default=None
            Numeric feature columns passed to the outer preprocessing builder
            when ``use_preprocess=True``.

        cat_encoder : str, default="ohe"
            Categorical encoder type passed to the outer preprocessing builder
            when ``use_preprocess=True``.

        Returns
        -------
        dict[str, Any]
            A compact training summary dictionary containing information such as:

            - input model type
            - task type
            - number of first-layer estimators
            - first-layer estimator names
            - final estimator class name
            - stacking internal CV folds
            - passthrough setting
            - classification stack-method
            - outer CV usage
            - outer CV folds
            - scoring method
            - preprocessing usage
            - best parameters
            - best score
            - feature names

        Notes
        -----
        The fitted pipeline itself is stored internally in ``self.model_pipeline``
        by the inherited training workflow.

        The returned dictionary is intended as a compact run summary and is not
        a replacement for the fitted outer pipeline object.
        """
        self.input_model_type = (
            "StackingClassifier"
            if self.task == "classification"
            else "StackingRegressor"
        )

        stacking_model = self._build_stacking_model(
            estimators=estimators,
            final_estimator=final_estimator,
            cv=stacking_cv,
            n_jobs=n_jobs,
            passthrough=passthrough,
            stack_method=stack_method,
        )

        best_params, best_score = self.fit_with_grid(
            base_model=stacking_model,
            param_grid=param_grid,
            use_cv=use_cv,
            cv_folds=cv_folds,
            scoring=scoring,
            random_state=random_state,
            extra_steps=extra_steps,
            use_preprocess=use_preprocess,
            categorical_cols=categorical_cols,
            numeric_cols=numeric_cols,
            cat_encoder=cat_encoder,
        )

        return {
            "input_model_type": self.input_model_type,
            "task": self.task,
            "n_estimators": len(estimators),
            "estimator_names": [name for name, _ in estimators],
            "final_estimator": type(final_estimator).__name__,
            "stacking_cv": stacking_cv,
            "passthrough": passthrough,
            "stack_method": stack_method if self.task == "classification" else None,
            "use_cv": use_cv,
            "cv_folds": cv_folds if use_cv else None,
            "scoring": scoring,
            "use_preprocess": use_preprocess,
            "best_params": best_params,
            "best_score": best_score,
            "feature_names": self.feature_names,
        }

    # -------------------- Predict --------------------
    def predict_engine(
        self,
        X_data: Optional[pd.DataFrame] = None,
        preview: int = 5,
    ):
        """
        Generate predictions using the fitted stacking pipeline.

        This method calls ``predict()`` on the internally stored fitted outer
        pipeline. If no input data is provided, it falls back to ``self.X_test``.

        A short prediction preview is also cached into
        ``self.prediction_preview`` for later inspection.

        Parameters
        ----------
        X_data : pandas.DataFrame or None, default=None
            Input feature data for prediction. If ``None``, the method attempts
            to use ``self.X_test``.

        preview : int, default=5
            Number of predicted rows stored in ``self.prediction_preview``.

        Returns
        -------
        Any
            Prediction output returned by the fitted pipeline.

        Raises
        ------
        ValueError
            If the model pipeline has not been fitted yet.

        ValueError
            If ``X_data`` is ``None`` and ``self.X_test`` is also unavailable.

        Notes
        -----
        The cached ``prediction_preview`` is intended only for quick inspection.
        The full prediction result is still returned unchanged.
        """
        if self.model_pipeline is None:
            raise ValueError("⚠️ Train the model before prediction ‼️")

        if X_data is None:
            if self.X_test is None:
                raise ValueError("⚠️ No X_data provided and X_test is unavailable ‼️")
            X_data = self.X_test

        preds = self.model_pipeline.predict(X_data)

        try:
            self.prediction_preview = preds[:preview]
        except Exception:
            self.prediction_preview = preds

        return preds

    # -------------------- Predict probability --------------------
    def predict_proba_engine(
        self,
        X_data: Optional[pd.DataFrame] = None,
    ):
        """
        Predict class probabilities using the fitted stacking classification pipeline.

        This method is only valid for classification tasks. It calls
        ``predict_proba()`` on the internally stored fitted outer pipeline.

        If no input data is provided, the method falls back to ``self.X_test``.

        Parameters
        ----------
        X_data : pandas.DataFrame or None, default=None
            Input feature data for probability prediction. If ``None``, the
            method attempts to use ``self.X_test``.

        Returns
        -------
        Any
            Probability prediction output returned by ``predict_proba()``.
            This is typically a NumPy array of class probabilities.

        Raises
        ------
        ValueError
            If the current task is not classification.

        ValueError
            If the model pipeline has not been fitted yet.

        ValueError
            If ``X_data`` is ``None`` and ``self.X_test`` is also unavailable.

        AttributeError
            If the fitted pipeline does not support ``predict_proba()``.

        Notes
        -----
        This method should only be used in classification workflows.
        """
        if self.task != "classification":
            raise ValueError("⚠️ predict_proba_engine() is only for classification ‼️")

        if self.model_pipeline is None:
            raise ValueError("⚠️ Train the model before predict_proba ‼️")

        if X_data is None:
            if self.X_test is None:
                raise ValueError("⚠️ No X_data provided and X_test is unavailable ‼️")
            X_data = self.X_test

        if not hasattr(self.model_pipeline, "predict_proba"):
            raise AttributeError(
                "⚠️ This fitted stacking pipeline does not support predict_proba ‼️"
            )

        return self.model_pipeline.predict_proba(X_data)

    # -------------------- Fitted stacking estimator getter --------------------
    def get_fitted_stacking_estimator(self):
        """
        Return the fitted final stacking estimator from the outer pipeline.

        This method retrieves the final stacking estimator step stored inside
        ``self.model_pipeline.named_steps`` using ``self.step_name``.

        It is useful when direct access to the fitted sklearn
        ``StackingClassifier`` or ``StackingRegressor`` object is needed after
        the outer pipeline has already been built and fitted.

        Returns
        -------
        Any
            The fitted final stacking estimator stored in the pipeline.
            This is typically a ``StackingClassifier`` or ``StackingRegressor``.

        Raises
        ------
        ValueError
            If ``self.model_pipeline`` is not fitted or unavailable.

        KeyError
            If the expected final estimator step name does not exist in
            ``self.model_pipeline.named_steps``.

        Notes
        -----
        This method returns only the final stacking estimator, not the full
        preprocessing-plus-model pipeline. Use ``self.model_pipeline`` directly
        when access to the full outer pipeline is needed.
        """
        if self.model_pipeline is None:
            raise ValueError("⚠️ model_pipeline is not fitted yet ‼️")

        if self.step_name not in self.model_pipeline.named_steps:
            raise KeyError(f"⚠️ Step '{self.step_name}' not found in model_pipeline ‼️")

        return self.model_pipeline.named_steps[self.step_name]


# =================================================
