# -------------------- Import Modules --------------------
from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence, Tuple

import pandas as pd
from sklearn.ensemble import VotingClassifier, VotingRegressor

from Apollo.Backbone.Ensemble_BaseConfig import EnsembleBaseModelConfig


# -------------------- Voting Missioner --------------------
class Voting_Missioner(EnsembleBaseModelConfig):
    """
    Mission-layer base class for sklearn voting ensemble workflows.

    This class centralizes shared logic for voting-based ensemble models so that
    child model classes can focus on task-specific configuration rather than
    repeatedly implementing the same training and prediction flow.

    The class supports both classification and regression voting ensembles:

    - ``VotingClassifier`` for classification tasks
    - ``VotingRegressor`` for regression tasks

    Main responsibilities include:

    - validating estimator lists used in the ensemble
    - validating voting strategy for classification
    - validating optional estimator weights
    - building the proper sklearn voting estimator based on task type
    - fitting the voting model through the inherited
      ``fit_with_grid(...)`` training pipeline
    - generating predictions from the fitted pipeline
    - generating probability predictions for classification tasks
    - retrieving the fitted final voting estimator from the outer pipeline

    Parameters
    ----------
    cleaned_X_data : pandas.DataFrame or None, optional
        Feature dataset passed from the inherited base configuration layer.

    cleaned_Y_data : pandas.Series, pandas.DataFrame, or None, optional
        Target dataset passed from the inherited base configuration layer.

    Attributes
    ----------
    task : str
        Task type defined by child classes. Expected values are
        ``"classification"`` or ``"regression"``.

    multioutput_scorer : Any
        Multi-output scoring configuration defined by child classes.

    input_model_type : str or None
        Name of the current input ensemble model type recorded during fitting.

    model_pipeline : sklearn.pipeline.Pipeline or None
        Final fitted outer pipeline created during training.

    prediction_preview : Any
        Cached prediction preview generated by ``predict_engine()``.

    feature_names : list[str] or None
        Feature names captured from the fitted training pipeline.

    Notes
    -----
    This is a mission-layer helper base class and is not usually intended to be
    instantiated directly. Instead, task-specific child classes should define
    the correct ``task`` value and call these shared methods.

    This class supports two preprocessing styles:

    1. outer preprocessing via ``fit_with_grid(use_preprocess=True)``
    2. estimator-owned pipelines via ``fit_with_grid(use_preprocess=False)``

    Typical child classes include:

    - ``VotingClassifier_Model``
    - ``VotingRegressor_Model``
    """

    # -------------------- Validation for voting type --------------------
    def _validate_voting_type(self, voting: str):
        """
        Validate the voting strategy for classification tasks.

        This helper normalizes the input voting string and checks whether it is a
        supported sklearn voting mode for ``VotingClassifier``.

        Supported voting strategies are:

        - ``"hard"``
        - ``"soft"``

        Parameters
        ----------
        voting : str
            Voting strategy string provided by the caller.

        Returns
        -------
        None

        Raises
        ------
        ValueError
            If ``voting`` is not one of ``"hard"`` or ``"soft"``.

        Notes
        -----
        This validation is only meaningful for classification workflows.
        Regression voting uses ``VotingRegressor`` and does not require a voting
        mode string.
        """
        voting = voting.lower().strip()
        if voting not in {"hard", "soft"}:
            raise ValueError("⚠️ voting must be 'hard' or 'soft' ‼️")

    # -------------------- Validation for weights --------------------
    def _validate_weights(
        self,
        estimators: Sequence[Tuple[str, Any]],
        weights: Optional[List[float]] = None,
    ):
        """
        Validate optional estimator weights for a voting ensemble.

        This helper checks whether the provided ``weights`` object has a valid
        container type and whether its length matches the number of estimators
        in the ensemble.

        Parameters
        ----------
        estimators : Sequence[Tuple[str, Any]]
            Sequence of estimator-name and estimator-object pairs used to build
            the voting ensemble.

        weights : list[float] or tuple[float, ...] or None, default=None
            Optional weight values aligned with the estimator order. If ``None``,
            no weighting is applied and sklearn uses uniform voting behavior.

        Returns
        -------
        None

        Raises
        ------
        TypeError
            If ``weights`` is provided but is not a ``list`` or ``tuple``.

        ValueError
            If the number of provided weights does not match the number of
            estimators.

        Notes
        -----
        This method only validates structure and alignment. It does not enforce
        positivity, normalization, or numeric type beyond what sklearn later
        accepts internally.
        """
        if weights is None:
            return

        if not isinstance(weights, (list, tuple)):
            raise TypeError("⚠️ weights must be a list or tuple ‼️")

        if len(weights) != len(estimators):
            raise ValueError("⚠️ weights length must match the number of estimators ‼️")

    # -------------------- Build voting estimator --------------------
    def _build_voting_model(
        self,
        estimators: Sequence[Tuple[str, Any]],
        voting: str = "hard",
        weights: Optional[List[float]] = None,
        n_jobs: Optional[int] = -1,
        flatten_transform: bool = True,
    ):
        """
        Build a sklearn voting ensemble estimator based on the current task type.

        This method first validates the estimator collection and optional
        estimator weights, then constructs either a ``VotingClassifier`` or
        ``VotingRegressor`` depending on ``self.task``.

        For classification tasks, the voting strategy is also validated and
        passed into ``VotingClassifier``.

        Parameters
        ----------
        estimators : Sequence[Tuple[str, Any]]
            Sequence of estimator-name and estimator-object pairs, for example::

                [
                    ("knn", knn_model),
                    ("svm", svm_model),
                    ("rf", rf_model),
                ]

            At least two estimators are required.

        voting : str, default="hard"
            Voting strategy for classification tasks.

            Supported values:
            - ``"hard"``
            - ``"soft"``

            This parameter is ignored for regression tasks.

        weights : list[float] or None, default=None
            Optional estimator weights aligned with the estimator sequence.

        n_jobs : int or None, default=-1
            Number of parallel jobs used by sklearn voting estimators where
            supported.

        flatten_transform : bool, default=True
            Parameter passed to ``VotingClassifier`` only.

            This mainly affects the output format of ``transform()`` when soft
            voting is used. It is ignored for regression tasks.

        Returns
        -------
        sklearn.ensemble.VotingClassifier or sklearn.ensemble.VotingRegressor
            A constructed sklearn voting ensemble estimator matching the current
            task type.

        Raises
        ------
        ValueError
            If ``self.task`` is not ``"classification"`` or ``"regression"``.

        Notes
        -----
        Estimator-list validation is delegated to ``self._validate_estimators(...)``,
        which is inherited from the ensemble base layer.

        This method only builds the sklearn estimator object. Fitting is handled
        separately by ``voting_fit_engine()`` through ``fit_with_grid(...)``.
        """
        # ---------- Check voting estimator and weights ----------
        checked_estimators = self._validate_estimators(
            estimators=estimators,
            min_estimators=2,
        )
        self._validate_weights(checked_estimators, weights)

        # ---------- Build base esemble models ----------
        if self.task == "classification":  # Classification task
            self._validate_voting_type(voting)
            model = VotingClassifier(
                estimators=checked_estimators,
                voting=voting,
                weights=weights,
                n_jobs=n_jobs,
                flatten_transform=flatten_transform,
            )
            return model

        if self.task == "regression":  # Regression task
            model = VotingRegressor(
                estimators=checked_estimators,
                weights=weights,
                n_jobs=n_jobs,
            )
            return model
        raise ValueError("⚠️ task must be 'classification' or 'regression' ‼️")

    # -------------------- Voting fit engine --------------------
    def voting_fit_engine(
        self,
        estimators: Sequence[Tuple[str, Any]],
        use_cv: bool = False,
        cv_folds: int = 5,
        scoring: str = "f1_weighted",
        voting: str = "hard",
        weights: Optional[List[float]] = None,
        n_jobs: Optional[int] = -1,
        flatten_transform: bool = True,
        param_grid: Optional[Dict[str, Any]] = None,
        random_state: int = 42,
        extra_steps: Optional[List[Tuple[str, Any]]] = None,
        use_preprocess: bool = True,
        categorical_cols: Optional[List[str]] = None,
        numeric_cols: Optional[List[str]] = None,
        cat_encoder: str = "ohe",
    ) -> Dict[str, Any]:
        """
        Build and fit a voting ensemble model through the shared training pipeline.

        This method constructs the base voting estimator, sends it into the
        inherited ``fit_with_grid(...)`` workflow, and returns a compact summary
        dictionary describing the fitted voting run.

        Depending on configuration, training can be performed in two modes:

        - direct fit without cross-validation
        - grid-search fit using ``GridSearchCV``

        Outer preprocessing can also be enabled or disabled depending on whether
        preprocessing is handled by the shared pipeline or already owned by the
        inner estimators.

        Parameters
        ----------
        estimators : Sequence[Tuple[str, Any]]
            Sequence of estimator-name and estimator-object pairs used as voting
            base learners.

        use_cv : bool, default=False
            Whether to perform cross-validation with ``GridSearchCV``.

        cv_folds : int, default=5
            Number of folds used when ``use_cv=True``.

        scoring : str, default="f1_weighted"
            sklearn scoring string used for single-output model selection.

            Common examples include:

            Classification:
            - ``"accuracy"``
            - ``"f1"``
            - ``"f1_weighted"``
            - ``"roc_auc"``

            Regression:
            - ``"r2"``
            - ``"neg_mean_squared_error"``
            - ``"neg_mean_absolute_error"``

        voting : str, default="hard"
            Voting strategy for classification tasks.

            Supported values:
            - ``"hard"``
            - ``"soft"``

            This parameter is ignored automatically for regression tasks.

        weights : list[float] or None, default=None
            Optional estimator weights aligned with the input estimator order.

        n_jobs : int or None, default=-1
            Number of parallel jobs used by the voting estimator where supported.

        flatten_transform : bool, default=True
            Classification-only parameter passed to ``VotingClassifier``.
            Mainly relevant when calling ``transform()`` under soft voting.

        param_grid : dict[str, Any] or None, default=None
            Parameter grid passed to ``fit_with_grid(...)`` for cross-validation.

            Parameter names should use the outer pipeline step prefix.

            Examples
            --------
            Classification::

                {
                    "classifier__voting": ["hard", "soft"],
                    "classifier__weights": [[1, 1, 1], [2, 1, 1]],
                }

            Regression::

                {
                    "regressor__weights": [[1, 1, 1], [2, 1, 1]],
                }

        random_state : int, default=42
            Random seed forwarded to CV splitter construction.

        extra_steps : list[tuple[str, Any]] or None, default=None
            Optional pipeline steps inserted between preprocessing and the final
            voting estimator.

        use_preprocess : bool, default=True
            Whether to include outer preprocessing in the training pipeline.

        categorical_cols : list[str] or None, default=None
            Categorical feature columns passed to the outer preprocessing builder
            when ``use_preprocess=True``.

        numeric_cols : list[str] or None, default=None
            Numeric feature columns passed to the outer preprocessing builder
            when ``use_preprocess=True``.

        cat_encoder : str, default="ohe"
            Categorical encoder type passed to the outer preprocessing builder
            when ``use_preprocess=True``.

        Returns
        -------
        dict[str, Any]
            A compact training summary dictionary containing information such as:

            - input model type
            - task type
            - number of estimators
            - estimator names
            - voting mode
            - weights
            - CV usage
            - CV folds
            - scoring method
            - preprocessing usage
            - best parameters
            - best score
            - feature names

        Notes
        -----
        The fitted pipeline itself is stored internally in ``self.model_pipeline``
        by the inherited training workflow.

        The returned dictionary is intended as a compact run summary and is not
        a replacement for the full fitted pipeline object.

        For regression tasks, the returned ``"voting"`` field is set to ``None``
        because ``VotingRegressor`` does not use hard/soft voting modes.
        """
        # ---------- Record model type ----------
        self.input_model_type = (
            "VotingClassifier" if self.task == "classification" else "VotingRegressor"
        )

        # ---------- Get base voting model ----------
        voting_model = self._build_voting_model(
            estimators=estimators,
            voting=voting,
            weights=weights,
            n_jobs=n_jobs,
            flatten_transform=flatten_transform,
        )

        # ---------- CV training ----------
        best_params, best_score = self.fit_with_grid(
            base_model=voting_model,
            param_grid=param_grid,
            use_cv=use_cv,
            cv_folds=cv_folds,
            scoring=scoring,
            random_state=random_state,
            extra_steps=extra_steps,
            use_preprocess=use_preprocess,
            categorical_cols=categorical_cols,
            numeric_cols=numeric_cols,
            cat_encoder=cat_encoder,
        )

        return {
            "input_model_type": self.input_model_type,
            "task": self.task,
            "n_estimators": len(estimators),
            "estimator_names": [name for name, _ in estimators],
            "voting": voting if self.task == "classification" else None,
            "weights": list(weights) if weights is not None else None,
            "use_cv": use_cv,
            "cv_folds": cv_folds if use_cv else None,
            "scoring": scoring,
            "use_preprocess": use_preprocess,
            "best_params": best_params,
            "best_score": best_score,
            "feature_names": self.feature_names,
        }

    # -------------------- Predict --------------------
    def predict_engine(
        self,
        X_data: Optional[pd.DataFrame] = None,
        preview: int = 5,
    ):
        """
        Generate predictions using the fitted voting pipeline.

        This method calls ``predict()`` on the internally stored fitted pipeline.
        If no input data is provided, it falls back to ``self.X_test``.

        A small prediction preview is also cached into
        ``self.prediction_preview`` for later inspection.

        Parameters
        ----------
        X_data : pandas.DataFrame or None, default=None
            Input feature data for prediction. If ``None``, the method attempts
            to use ``self.X_test``.

        preview : int, default=5
            Number of predicted rows to store in ``self.prediction_preview``.

        Returns
        -------
        Any
            Prediction output returned by the fitted pipeline. This is typically
            a NumPy array, pandas Series, or similar sklearn-compatible result.

        Raises
        ------
        ValueError
            If the model pipeline has not been fitted yet.

        ValueError
            If ``X_data`` is ``None`` and ``self.X_test`` is also unavailable.

        Notes
        -----
        The cached ``prediction_preview`` is meant for quick inspection only.
        It does not alter the returned full prediction result.
        """
        if self.model_pipeline is None:
            raise ValueError("⚠️ Train the model before prediction ‼️")

        if X_data is None:
            if self.X_test is None:
                raise ValueError("⚠️ No X_data provided and X_test is unavailable ‼️")
            X_data = self.X_test

        preds = self.model_pipeline.predict(X_data)

        try:
            self.prediction_preview = preds[:preview]
        except Exception:
            self.prediction_preview = preds

        return preds

    # -------------------- Predict probability --------------------
    def predict_proba_engine(
        self,
        X_data: Optional[pd.DataFrame] = None,
    ):
        """
        Predict class probabilities using the fitted voting classification pipeline.

        This method is only valid for classification tasks. It calls
        ``predict_proba()`` on the internally stored fitted pipeline.

        If no input data is provided, the method falls back to ``self.X_test``.

        Parameters
        ----------
        X_data : pandas.DataFrame or None, default=None
            Input feature data for probability prediction. If ``None``, the
            method attempts to use ``self.X_test``.

        Returns
        -------
        Any
            Probability prediction output returned by ``predict_proba()``.
            This is typically a NumPy array of class probabilities.

        Raises
        ------
        ValueError
            If the current task is not classification.

        ValueError
            If the model pipeline has not been fitted yet.

        ValueError
            If ``X_data`` is ``None`` and ``self.X_test`` is also unavailable.

        AttributeError
            If the fitted pipeline does not support ``predict_proba()``.

        Notes
        -----
        In voting classification workflows, probability prediction usually
        requires:

        - ``voting="soft"``
        - base estimators that support ``predict_proba()``

        Even in classification mode, this method may fail if the fitted voting
        estimator or wrapped pipeline does not expose probability prediction.
        """
        if self.task != "classification":
            raise ValueError("⚠️ predict_proba_engine() is only for classification ‼️")

        if self.model_pipeline is None:
            raise ValueError("⚠️ Train the model before predict_proba ‼️")

        if X_data is None:
            if self.X_test is None:
                raise ValueError("⚠️ No X_data provided and X_test is unavailable ‼️")
            X_data = self.X_test

        if not hasattr(self.model_pipeline, "predict_proba"):
            raise AttributeError(
                "⚠️ This fitted voting pipeline does not support predict_proba ‼️"
            )

        return self.model_pipeline.predict_proba(X_data)

    # -------------------- Fitted voting estimator getter --------------------
    def get_fitted_voting_estimator(self):
        """
        Return the fitted final voting estimator from the outer model pipeline.

        This method retrieves the final voting estimator step stored inside
        ``self.model_pipeline.named_steps`` using ``self.step_name``.

        It is useful when direct access to the fitted sklearn
        ``VotingClassifier`` or ``VotingRegressor`` object is needed after the
        outer training pipeline has already been constructed.

        Returns
        -------
        Any
            The fitted final voting estimator stored in the pipeline.
            This is typically a ``VotingClassifier`` or ``VotingRegressor``.

        Raises
        ------
        ValueError
            If ``self.model_pipeline`` is not fitted or unavailable.

        KeyError
            If the expected final estimator step name does not exist in
            ``self.model_pipeline.named_steps``.

        Notes
        -----
        This method returns only the final voting estimator, not the full outer
        pipeline. Use ``self.model_pipeline`` directly when access to the full
        preprocessing-plus-model pipeline is required.
        """
        if self.model_pipeline is None:
            raise ValueError("⚠️ model_pipeline is not fitted yet ‼️")

        if self.step_name not in self.model_pipeline.named_steps:
            raise KeyError(f"⚠️ Step '{self.step_name}' not found in model_pipeline ‼️")

        return self.model_pipeline.named_steps[self.step_name]


# =================================================
