# -------------------- Import Modules --------------------
from __future__ import annotations

import os
import time
from typing import Any, Dict, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    confusion_matrix,
    f1_score,
    mean_absolute_error,
    mean_squared_error,
    precision_score,
    r2_score,
    recall_score,
)

from Apollo.Backbone.Ensemble_BaseConfig import report_root
from Apollo.Ensemble_Missioner.Voting_Missioner import Voting_Missioner


# -------------------- Voting classifier model --------------------
class VotingClassifier_Model(Voting_Missioner):
    """
    Train, evaluate, and visualize a voting-based classification model.

    This class provides the model-layer workflow for classification tasks based on
    ``VotingClassifier`` through the inherited voting mission pipeline. It is
    responsible for coordinating estimator assembly, optional preprocessing,
    optional cross-validation, model fitting, prediction, evaluation, and
    confusion-matrix visualization.

    The class supports both single-output and multi-output classification
    workflows. For multi-output tasks, evaluation metrics are computed for each
    target column and then aggregated by mean.

    Inherited Responsibilities
    --------------------------
    This class relies on inherited mission/base-layer utilities for:
    - train/test split preparation
    - preprocessing pipeline construction
    - voting estimator fitting
    - feature-name tracking
    - multi-output target detection

    Attributes
    ----------
    task : str
        Read-only property returning ``"classification"``.

    Notes
    -----
    Before calling ``train()``, the dataset must already be split by
    ``train_test_split_engine()`` so that ``X_train``, ``X_test``, ``Y_train``,
    and ``Y_test`` are available.

    The fitted model is stored in ``self.model_pipeline``. Predictions generated
    during evaluation are stored in ``self.y_train_pred`` and ``self.y_test_pred``.
    """

    # -------------------- Task type --------------------
    @property
    def task(self) -> str:
        """
        Return the task type handled by this model class.

        Returns
        -------
        str
            Fixed task identifier ``"classification"``.

        Notes
        -----
        This property is typically used by shared mission/base-layer logic to
        decide which estimator family, scoring behavior, or evaluation path
        should be applied.
        """
        return "classification"

    # -------------------- Multi-output scoring --------------------
    @staticmethod
    def multioutput_scorer(y_true, y_pred) -> float:
        """
        Compute a classification score for single-output or multi-output targets.

        This scorer is designed for use in GridSearchCV or related model-selection
        workflows. For single-output classification, it returns the weighted F1
        score directly. For multi-output classification, it computes the weighted
        F1 score separately for each target column and returns the arithmetic mean
        across all target columns.

        Parameters
        ----------
        y_true : pandas.Series, pandas.DataFrame, or numpy.ndarray
            Ground-truth labels.
            - If 1-dimensional, the task is treated as single-output classification.
            - If 2-dimensional, the task is treated as multi-output classification.

        y_pred : pandas.Series, pandas.DataFrame, or numpy.ndarray
            Predicted labels generated by the estimator. Its structure should align
            with ``y_true``.

        Returns
        -------
        float
            Weighted F1 score for single-output classification, or the mean of
            per-target weighted F1 scores for multi-output classification.

        Notes
        -----
        If ``y_true`` is not a DataFrame in multi-output mode, it is converted to
        ``pandas.DataFrame`` first. If ``y_pred`` is not a DataFrame, it is also
        converted so that target-column alignment can be preserved.

        This scorer assumes that each target column represents a separate
        classification problem.

        Examples
        --------
        Single-output classification:
            weighted F1(y_true, y_pred)

        Multi-output classification:
            mean([
                weighted F1(y_true[col_1], y_pred[col_1]),
                weighted F1(y_true[col_2], y_pred[col_2]),
                ...
            ])
        """
        # ---------- Single-output ----------
        if isinstance(y_true, pd.Series) or (
            isinstance(y_true, np.ndarray) and y_true.ndim == 1
        ):
            return float(f1_score(y_true, y_pred, average="weighted"))

        # ---------- Multi-output ----------
        if not isinstance(y_true, pd.DataFrame):
            y_true = pd.DataFrame(y_true)

        if not isinstance(y_pred, pd.DataFrame):
            y_pred = pd.DataFrame(y_pred, columns=y_true.columns)

        scores = [
            f1_score(y_true[col], y_pred[col], average="weighted")
            for col in y_true.columns
        ]
        return float(np.mean(scores)) if scores else 0.0

    # -------------------- Train voting classifier --------------------
    def train(
        self,
        estimators: Sequence[Tuple[str, Any]],
        use_cv: bool = False,
        cv_folds: int = 5,
        scoring: str = "f1_weighted",
        voting: str = "hard",
        weights: Optional[List[float]] = None,
        n_jobs: Optional[int] = None,
        flatten_transform: bool = True,
        param_grid: Optional[Dict[str, Any]] = None,
        random_state: int = 42,
        extra_steps: Optional[List[Tuple[str, Any]]] = None,
        use_preprocess: bool = True,
        categorical_cols: Optional[List[str]] = None,
        numeric_cols: Optional[List[str]] = None,
        cat_encoder: str = "ohe",
    ) -> Dict[str, Any]:
        """
        Train a voting classifier and return a full training summary.

        This method fits a classification voting ensemble using the inherited
        ``voting_fit_engine()`` workflow, then evaluates the fitted model on both
        the training and test sets through ``model_evaluation_engine()``.

        The method supports optional preprocessing, optional intermediate pipeline
        steps, optional GridSearchCV, and both hard and soft voting strategies.

        Parameters
        ----------
        estimators : Sequence[Tuple[str, Any]]
            List or sequence of base estimators used by the voting ensemble.
            Each item must be a ``(name, estimator)`` tuple compatible with
            scikit-learn voting estimators.

        use_cv : bool, default=False
            Whether to perform hyperparameter search with GridSearchCV.

        cv_folds : int, default=5
            Number of cross-validation folds used when ``use_cv=True``.

        scoring : str, default="f1_weighted"
            Scikit-learn scoring name used in single-output classification during
            cross-validation.

        voting : str, default="hard"
            Voting strategy for ``VotingClassifier``.
            Supported values usually include:
            - ``"hard"`` : majority class vote
            - ``"soft"`` : average predicted probabilities

        weights : list[float] or None, default=None
            Optional weights assigned to each estimator in the voting ensemble.
            If ``None``, equal weighting is used.

        n_jobs : int or None, default=None
            Number of parallel jobs used by the voting estimator where supported.
            ``None`` means scikit-learn default behavior.

        flatten_transform : bool, default=True
            Whether transformed outputs from estimators should be flattened when
            supported by the underlying voting implementation.

        param_grid : dict[str, Any] or None, default=None
            Hyperparameter grid passed to GridSearchCV for outer pipeline search.
            If ``None``, no parameter search grid is applied.

        random_state : int, default=42
            Random seed used for CV-related reproducibility where applicable.

        extra_steps : list[tuple[str, Any]] or None, default=None
            Optional extra pipeline steps inserted between preprocessing and the
            final voting estimator.

        use_preprocess : bool, default=True
            Whether to include a preprocessing step in the outer pipeline.

        categorical_cols : list[str] or None, default=None
            Categorical feature-column names passed to the preprocessing builder
            when preprocessing is enabled.

        numeric_cols : list[str] or None, default=None
            Numeric feature-column names passed to the preprocessing builder when
            preprocessing is enabled.

        cat_encoder : str, default="ohe"
            Encoding strategy for categorical columns when preprocessing is enabled.
            This value is forwarded to the preprocessing builder.

        Returns
        -------
        dict[str, Any]
            A training summary dictionary containing fitted-model information and
            evaluation results. Typical contents include:
            - inherited fit summary fields from ``voting_fit_engine()``
            - ``feature_names_len`` : number of tracked transformed feature names
            - ``evaluation`` : evaluation dictionary returned by
              ``model_evaluation_engine()``

        Raises
        ------
        ValueError
            If ``X_train`` or ``Y_train`` is not available before training.

        Notes
        -----
        This method assumes that train/test splitting has already been completed.

        The fitted pipeline is stored in ``self.model_pipeline`` by the inherited
        fitting workflow. After fitting, evaluation is immediately performed on
        both train and test data.

        For multi-output classification, evaluation results include both per-target
        metrics and averaged metrics.
        """
        if self.X_train is None or self.Y_train is None:
            raise ValueError("⚠️ Run train_test_split_engine() before training ‼️")

        # ---------- Training summary ----------
        fit_summary = self.voting_fit_engine(
            estimators=estimators,
            use_cv=use_cv,
            cv_folds=cv_folds,
            scoring=scoring,
            voting=voting,
            weights=weights,
            n_jobs=n_jobs,
            flatten_transform=flatten_transform,
            param_grid=param_grid,
            random_state=random_state,
            extra_steps=extra_steps,
            use_preprocess=use_preprocess,
            categorical_cols=categorical_cols,
            numeric_cols=numeric_cols,
            cat_encoder=cat_encoder,
        )

        # ---------- Evaluations ----------
        eval_results = self.model_evaluation_engine()

        return {
            **fit_summary,
            "feature_names_len": (
                None if self.feature_names is None else len(self.feature_names)
            ),
            "evaluation": eval_results,
        }

    # -------------------- Classification evaluation --------------------
    def model_evaluation_engine(self) -> Dict[str, Any]:
        """
        Evaluate the fitted classifier on training and test datasets.

        This method generates predictions from the fitted model pipeline for both
        ``X_train`` and ``X_test``, then computes classification metrics.

        Evaluation Behavior
        -------------------
        Single-output classification:
            - accuracy
            - weighted precision
            - weighted recall
            - weighted F1

        Multi-output classification:
            - per-target accuracy
            - per-target weighted precision
            - per-target weighted recall
            - per-target weighted F1
            - mean of each metric across all target columns

        Returns
        -------
        dict[str, Any]
            Evaluation-result dictionary.

            For single-output classification, the returned dictionary contains:
            - ``train_accuracy``
            - ``test_accuracy``
            - ``train_precision_weighted``
            - ``test_precision_weighted``
            - ``train_recall_weighted``
            - ``test_recall_weighted``
            - ``train_f1_weighted``
            - ``test_f1_weighted``

            For multi-output classification, the returned dictionary contains:
            - mean metrics across targets
            - per-target metric dictionaries for train and test data

        Raises
        ------
        ValueError
            If ``self.model_pipeline`` is not fitted or missing.

        ValueError
            If train/test feature or target data is unavailable.

        Notes
        -----
        Predictions are stored in:
        - ``self.y_train_pred``
        - ``self.y_test_pred``

        If target-side label encoding was applied during training, both
        predictions and true labels are decoded back to original labels before
        metric computation.

        For multi-output classification, decoded predictions may be stored as a
        ``pandas.DataFrame`` whose column names align with the target columns.

        Weighted precision and weighted recall are computed with
        ``zero_division=0`` to avoid warnings when a class has no predicted
        samples.
        """
        if self.model_pipeline is None:
            raise ValueError("⚠️ Train the model before evaluation ‼️")

        if (
            self.X_train is None
            or self.X_test is None
            or self.Y_train is None
            or self.Y_test is None
        ):
            raise ValueError("⚠️ Train/test data is unavailable for evaluation ‼️")

        # ---------- Raw encoded predictions ----------
        train_pred_raw = self.model_pipeline.predict(self.X_train)
        test_pred_raw = self.model_pipeline.predict(self.X_test)

        # ---------- Decode predictions ----------
        self.y_train_pred = self._maybe_decode_predictions(train_pred_raw)
        self.y_test_pred = self._maybe_decode_predictions(test_pred_raw)

        # ---------- Decode true labels ----------
        y_train_true = self.decode_target_labels(self.Y_train)
        y_test_true = self.decode_target_labels(self.Y_test)

        # ---------- Multi-output classification ----------
        if self._is_multi_output(self.Y_test):
            train_accuracy_per_target = {
                col: float(accuracy_score(y_train_true[col], self.y_train_pred[col]))
                for col in y_train_true.columns
            }
            test_accuracy_per_target = {
                col: float(accuracy_score(y_test_true[col], self.y_test_pred[col]))
                for col in y_test_true.columns
            }

            train_precision_weighted_per_target = {
                col: float(
                    precision_score(
                        y_train_true[col],
                        self.y_train_pred[col],
                        average="weighted",
                        zero_division=0,
                    )
                )
                for col in y_train_true.columns
            }
            test_precision_weighted_per_target = {
                col: float(
                    precision_score(
                        y_test_true[col],
                        self.y_test_pred[col],
                        average="weighted",
                        zero_division=0,
                    )
                )
                for col in y_test_true.columns
            }

            train_recall_weighted_per_target = {
                col: float(
                    recall_score(
                        y_train_true[col],
                        self.y_train_pred[col],
                        average="weighted",
                        zero_division=0,
                    )
                )
                for col in y_train_true.columns
            }
            test_recall_weighted_per_target = {
                col: float(
                    recall_score(
                        y_test_true[col],
                        self.y_test_pred[col],
                        average="weighted",
                        zero_division=0,
                    )
                )
                for col in y_test_true.columns
            }

            train_f1_weighted_per_target = {
                col: float(
                    f1_score(
                        y_train_true[col],
                        self.y_train_pred[col],
                        average="weighted",
                    )
                )
                for col in y_train_true.columns
            }
            test_f1_weighted_per_target = {
                col: float(
                    f1_score(
                        y_test_true[col],
                        self.y_test_pred[col],
                        average="weighted",
                    )
                )
                for col in y_test_true.columns
            }

            return {
                "train_accuracy_mean": float(
                    np.mean(list(train_accuracy_per_target.values()))
                ),
                "test_accuracy_mean": float(
                    np.mean(list(test_accuracy_per_target.values()))
                ),
                "train_precision_weighted_mean": float(
                    np.mean(list(train_precision_weighted_per_target.values()))
                ),
                "test_precision_weighted_mean": float(
                    np.mean(list(test_precision_weighted_per_target.values()))
                ),
                "train_recall_weighted_mean": float(
                    np.mean(list(train_recall_weighted_per_target.values()))
                ),
                "test_recall_weighted_mean": float(
                    np.mean(list(test_recall_weighted_per_target.values()))
                ),
                "train_f1_weighted_mean": float(
                    np.mean(list(train_f1_weighted_per_target.values()))
                ),
                "test_f1_weighted_mean": float(
                    np.mean(list(test_f1_weighted_per_target.values()))
                ),
                "train_accuracy_per_target": train_accuracy_per_target,
                "test_accuracy_per_target": test_accuracy_per_target,
                "train_precision_weighted_per_target": train_precision_weighted_per_target,
                "test_precision_weighted_per_target": test_precision_weighted_per_target,
                "train_recall_weighted_per_target": train_recall_weighted_per_target,
                "test_recall_weighted_per_target": test_recall_weighted_per_target,
                "train_f1_weighted_per_target": train_f1_weighted_per_target,
                "test_f1_weighted_per_target": test_f1_weighted_per_target,
            }

        # ---------- Single-output classification ----------
        return {
            "train_accuracy": float(accuracy_score(y_train_true, self.y_train_pred)),
            "test_accuracy": float(accuracy_score(y_test_true, self.y_test_pred)),
            "train_precision_weighted": float(
                precision_score(
                    y_train_true,
                    self.y_train_pred,
                    average="weighted",
                    zero_division=0,
                )
            ),
            "test_precision_weighted": float(
                precision_score(
                    y_test_true,
                    self.y_test_pred,
                    average="weighted",
                    zero_division=0,
                )
            ),
            "train_recall_weighted": float(
                recall_score(
                    y_train_true,
                    self.y_train_pred,
                    average="weighted",
                    zero_division=0,
                )
            ),
            "test_recall_weighted": float(
                recall_score(
                    y_test_true,
                    self.y_test_pred,
                    average="weighted",
                    zero_division=0,
                )
            ),
            "train_f1_weighted": float(
                f1_score(y_train_true, self.y_train_pred, average="weighted")
            ),
            "test_f1_weighted": float(
                f1_score(y_test_true, self.y_test_pred, average="weighted")
            ),
        }

    # -------------------- Confusion matrix engine --------------------
    def confusion_matrix_engine(
        self,
        target_col: str | None = None,
        normalize: str | None = None,
        save_fig: bool = False,
        folder_name: str = "Confusion_Matrix",
        file_name: str | None = None,
    ):
        """
        Plot and optionally save a confusion matrix for the fitted classifier.

        This method generates predictions on the test set and plots a confusion
        matrix using scikit-learn's ``ConfusionMatrixDisplay``.

        For single-output classification, the confusion matrix is computed directly
        from decoded ``Y_test`` and decoded predicted labels.

        For multi-output classification, a specific target column must be selected
        through ``target_col`` so that one confusion matrix can be plotted for that
        target at a time.

        Parameters
        ----------
        target_col : str or None, default=None
            Target-column name used for multi-output classification plotting.
            This parameter is required when ``Y_test`` is multi-output.
            It is ignored for single-output classification.

        normalize : str or None, default=None
            Normalization mode forwarded to ``sklearn.metrics.confusion_matrix()``.

            Common values include:
            - ``None``   : raw counts
            - ``"true"`` : normalize over true labels
            - ``"pred"`` : normalize over predicted labels
            - ``"all"``  : normalize over all entries

        save_fig : bool, default=False
            Whether to save the plotted figure as an image file.

        folder_name : str, default="Confusion_Matrix"
            Folder name created under ``report_root`` when ``save_fig=True``.

        file_name : str or None, default=None
            Custom output filename. If ``None``, an automatic filename is
            generated from the class name, optional target name, and timestamp.

        Returns
        -------
        None
            This method displays the plot with ``matplotlib.pyplot.show()`` and
            optionally saves it to disk.

        Raises
        ------
        ValueError
            If the model pipeline has not been trained.

        ValueError
            If test data is unavailable.

        ValueError
            If the task is multi-output classification and ``target_col`` is not
            provided.

        ValueError
            If ``target_col`` is not found in ``self.Y_test.columns``.

        Notes
        -----
        If target-side label encoding was applied during training, both true labels
        and predicted labels are decoded back to their original label values before
        confusion matrix computation.

        In multi-output classification workflows, decoded predictions may be
        represented as either:
        - a ``pandas.DataFrame`` with target-column names
        - a 2-dimensional array-like object whose column order matches
        ``self.Y_test.columns``

        When ``save_fig=True``, the figure is saved under:
        ``os.path.join(report_root, folder_name)``

        The plot title includes the class name and, for multi-output cases, the
        selected target column name.

        The displayed value format is:
        - integer counts when ``normalize is None``
        - 2-decimal float format when normalization is enabled

        The plot is closed with ``plt.close()`` after display to reduce figure
        accumulation in repeated plotting workflows.
        """
        if self.model_pipeline is None:
            raise ValueError("⚠️ Train the model before confusion matrix plotting ‼️")

        if self.X_test is None or self.Y_test is None:
            raise ValueError(
                "⚠️ Test data is unavailable for confusion matrix plotting ‼️"
            )

        y_pred = self.model_pipeline.predict(self.X_test)
        y_pred = self._maybe_decode_predictions(y_pred)

        y_true_plot_all = self.decode_target_labels(self.Y_test)

        # ---------- Multi-output ----------
        if self._is_multi_output(self.Y_test):
            if target_col is None:
                raise ValueError(
                    "⚠️ target_col is required for multi-output confusion matrix ‼️"
                )

            if target_col not in self.Y_test.columns:
                raise ValueError(f"⚠️ target_col '{target_col}' not found in Y_test ‼️")

            col_idx = list(self.Y_test.columns).index(target_col)
            y_true_plot = y_true_plot_all[target_col]

            if isinstance(y_pred, pd.DataFrame):
                y_pred_plot = y_pred[target_col]
            else:
                y_pred_plot = y_pred[:, col_idx]

            title = f"{self.__class__.__name__} Confusion Matrix ({target_col})"

        # ---------- Single-output ----------
        else:
            y_true_plot = y_true_plot_all
            y_pred_plot = y_pred
            title = f"{self.__class__.__name__} Confusion Matrix"

        cm = confusion_matrix(y_true_plot, y_pred_plot, normalize=normalize)
        disp = ConfusionMatrixDisplay(confusion_matrix=cm)

        plt.figure(figsize=(7, 6))
        disp.plot(values_format=".2f" if normalize else "d")
        plt.title(title)
        plt.tight_layout()

        if save_fig:
            save_folder = os.path.join(report_root, folder_name)
            os.makedirs(save_folder, exist_ok=True)

            if file_name is None:
                timestamp = time.strftime("%Y%m%d_%H%M%S")
                safe_suffix = f"_{target_col}" if target_col else ""
                file_name = f"{self.__class__.__name__}_confusion_matrix{safe_suffix}_{timestamp}.png"

            save_path = os.path.join(save_folder, file_name)
            plt.savefig(save_path, dpi=200, bbox_inches="tight")
            print(f"🔥 Confusion matrix figure saved: {save_path}")

        plt.show()


# -------------------- Voting regressor model --------------------
class VotingRegressor_Model(Voting_Missioner):
    """
    Train and evaluate a voting-based regression model.

    This class provides the model-layer workflow for regression tasks based on
    ``VotingRegressor`` through the inherited voting mission pipeline. It handles
    estimator assembly, optional preprocessing, optional cross-validation,
    fitting, prediction, and regression evaluation.

    The class supports both single-output and multi-output regression workflows.
    For multi-output tasks, metrics are computed separately for each target column
    and then aggregated by mean.

    Inherited Responsibilities
    --------------------------
    This class relies on inherited mission/base-layer utilities for:
    - train/test split preparation
    - preprocessing pipeline construction
    - voting estimator fitting
    - feature-name tracking
    - multi-output target detection

    Attributes
    ----------
    task : str
        Read-only property returning ``"regression"``.

    Notes
    -----
    Before calling ``train()``, the dataset must already be prepared by
    ``train_test_split_engine()``.

    The fitted estimator pipeline is stored in ``self.model_pipeline``. Prediction
    results generated during evaluation are stored in ``self.y_train_pred`` and
    ``self.y_test_pred``.
    """

    # -------------------- Task type --------------------
    @property
    def task(self) -> str:
        """
        Return the task type handled by this model class.

        Returns
        -------
        str
            Fixed task identifier ``"regression"``.

        Notes
        -----
        This property is typically used by shared model/mission logic to select
        regression-specific fitting and evaluation behavior.
        """
        return "regression"

    # -------------------- Multi-output scoring --------------------
    @staticmethod
    def multioutput_scorer(y_true, y_pred) -> float:
        """
        Compute a regression score for single-output or multi-output targets.

        This scorer is intended for use in GridSearchCV or related model-selection
        workflows. For single-output regression, it returns the R² score directly.
        For multi-output regression, it computes R² separately for each target
        column and returns the arithmetic mean across all targets.

        Parameters
        ----------
        y_true : pandas.Series, pandas.DataFrame, or numpy.ndarray
            Ground-truth target values.
            - If 1-dimensional, the task is treated as single-output regression.
            - If 2-dimensional, the task is treated as multi-output regression.

        y_pred : pandas.Series, pandas.DataFrame, or numpy.ndarray
            Predicted target values generated by the estimator.

        Returns
        -------
        float
            R² score for single-output regression, or the mean of per-target R²
            scores for multi-output regression.

        Notes
        -----
        If ``y_true`` is not already a DataFrame in multi-output mode, it is
        converted to one. ``y_pred`` is also converted when necessary so that
        column alignment can follow ``y_true.columns``.

        This scorer assumes that each output column represents an independent
        regression target.
        """
        # ---------- Single-output ----------
        if isinstance(y_true, pd.Series) or (
            isinstance(y_true, np.ndarray) and y_true.ndim == 1
        ):
            return float(r2_score(y_true, y_pred))

        # ---------- Multi-output ----------
        if not isinstance(y_true, pd.DataFrame):
            y_true = pd.DataFrame(y_true)

        if not isinstance(y_pred, pd.DataFrame):
            y_pred = pd.DataFrame(y_pred, columns=y_true.columns)

        scores = [r2_score(y_true[col], y_pred[col]) for col in y_true.columns]
        return float(np.mean(scores)) if scores else 0.0

    # -------------------- Train voting regressor --------------------
    def train(
        self,
        estimators: Sequence[Tuple[str, Any]],
        use_cv: bool = False,
        cv_folds: int = 5,
        scoring: str = "r2",
        weights: Optional[List[float]] = None,
        n_jobs: Optional[int] = None,
        param_grid: Optional[Dict[str, Any]] = None,
        random_state: int = 42,
        extra_steps: Optional[List[Tuple[str, Any]]] = None,
        use_preprocess: bool = True,
        categorical_cols: Optional[List[str]] = None,
        numeric_cols: Optional[List[str]] = None,
        cat_encoder: str = "ohe",
    ) -> Dict[str, Any]:
        """
        Train a voting regressor and return a full training summary.

        This method fits a regression voting ensemble using the inherited
        ``voting_fit_engine()`` workflow, then evaluates the fitted model on both
        the training and test sets through ``model_evaluation_engine()``.

        Parameters
        ----------
        estimators : Sequence[Tuple[str, Any]]
            List or sequence of base estimators used by the voting regressor.
            Each item must be a ``(name, estimator)`` tuple compatible with
            scikit-learn voting regressors.

        use_cv : bool, default=False
            Whether to perform hyperparameter search with GridSearchCV.

        cv_folds : int, default=5
            Number of cross-validation folds used when ``use_cv=True``.

        scoring : str, default="r2"
            Scikit-learn scoring name used in single-output regression during
            cross-validation.

        weights : list[float] or None, default=None
            Optional weights assigned to each estimator in the ensemble.
            If ``None``, equal weighting is used.

        n_jobs : int or None, default=None
            Number of parallel jobs used by the voting regressor where supported.

        param_grid : dict[str, Any] or None, default=None
            Hyperparameter grid passed to GridSearchCV for outer pipeline search.

        random_state : int, default=42
            Random seed used for CV-related reproducibility where applicable.

        extra_steps : list[tuple[str, Any]] or None, default=None
            Optional extra pipeline steps inserted between preprocessing and the
            final estimator.

        use_preprocess : bool, default=True
            Whether to include a preprocessing step in the outer pipeline.

        categorical_cols : list[str] or None, default=None
            Categorical feature-column names passed to the preprocessing builder
            when preprocessing is enabled.

        numeric_cols : list[str] or None, default=None
            Numeric feature-column names passed to the preprocessing builder when
            preprocessing is enabled.

        cat_encoder : str, default="ohe"
            Encoding strategy for categorical columns when preprocessing is enabled.

        Returns
        -------
        dict[str, Any]
            A training summary dictionary containing fit information and evaluation
            results. Typical contents include:
            - inherited fit summary fields from ``voting_fit_engine()``
            - ``feature_names_len`` : number of tracked transformed feature names
            - ``evaluation`` : evaluation dictionary returned by
              ``model_evaluation_engine()``

        Raises
        ------
        ValueError
            If ``X_train`` or ``Y_train`` is unavailable before training.

        Notes
        -----
        Internally, this method forwards regression training to the shared voting
        fit engine. Parameters such as ``voting="hard"`` and
        ``flatten_transform=True`` may be passed internally only for interface
        consistency and are ignored by the ``VotingRegressor`` flow.

        After fitting, evaluation is immediately performed on both train and test
        data.
        """
        if self.X_train is None or self.Y_train is None:
            raise ValueError("⚠️ Run train_test_split_engine() before training ‼️")

        # ---------- Training summary ----------
        fit_summary = self.voting_fit_engine(
            estimators=estimators,
            use_cv=use_cv,
            cv_folds=cv_folds,
            scoring=scoring,
            voting="hard",  # ignored automatically inside VotingRegressor flow
            weights=weights,
            n_jobs=n_jobs,
            flatten_transform=True,  # ignored automatically inside VotingRegressor flow
            param_grid=param_grid,
            random_state=random_state,
            extra_steps=extra_steps,
            use_preprocess=use_preprocess,
            categorical_cols=categorical_cols,
            numeric_cols=numeric_cols,
            cat_encoder=cat_encoder,
        )

        # ---------- Evaluations ----------
        eval_results = self.model_evaluation_engine()

        return {
            **fit_summary,
            "feature_names_len": (
                None if self.feature_names is None else len(self.feature_names)
            ),
            "evaluation": eval_results,
        }

    # -------------------- Regression evaluation --------------------
    def model_evaluation_engine(self) -> Dict[str, Any]:
        """
        Evaluate the fitted voting regressor on training and test datasets.

        This method generates predictions from the fitted model pipeline for both
        ``X_train`` and ``X_test``, then computes regression metrics.

        Evaluation Behavior
        -------------------
        Single-output regression:
            - R²
            - MAE
            - MSE
            - RMSE

        Multi-output regression:
            - per-target R²
            - per-target MAE
            - per-target MSE
            - per-target RMSE
            - mean of each metric across all target columns

        Returns
        -------
        dict[str, Any]
            Evaluation-result dictionary.

            For single-output regression, the returned dictionary contains:
            - ``train_r2``
            - ``test_r2``
            - ``train_mae``
            - ``test_mae``
            - ``train_mse``
            - ``test_mse``
            - ``train_rmse``
            - ``test_rmse``

            For multi-output regression, the returned dictionary contains:
            - mean metrics across targets
            - per-target metric dictionaries for train and test data

        Raises
        ------
        ValueError
            If ``self.model_pipeline`` is not fitted or missing.

        ValueError
            If train/test feature or target data is unavailable.

        Notes
        -----
        Predictions are stored in:
        - ``self.y_train_pred``
        - ``self.y_test_pred``

        For multi-output regression, this method assumes that prediction output is
        a 2-dimensional array whose column order matches the target-column order
        of ``self.Y_train`` and ``self.Y_test``.

        RMSE is derived from MSE by applying the square-root transformation.
        """
        if self.model_pipeline is None:
            raise ValueError("⚠️ Train the model before evaluation ‼️")

        if (
            self.X_train is None
            or self.X_test is None
            or self.Y_train is None
            or self.Y_test is None
        ):
            raise ValueError("⚠️ Train/test data is unavailable for evaluation ‼️")

        # ---------- Predict ----------
        self.y_train_pred = self.model_pipeline.predict(self.X_train)
        self.y_test_pred = self.model_pipeline.predict(self.X_test)

        # ---------- Get train and test dataset from multiple output ----------
        if self._is_multi_output(self.Y_test):
            train_r2_per_target = {
                col: float(r2_score(self.Y_train[col], self.y_train_pred[:, idx]))
                for idx, col in enumerate(self.Y_train.columns)
            }
            test_r2_per_target = {
                col: float(r2_score(self.Y_test[col], self.y_test_pred[:, idx]))
                for idx, col in enumerate(self.Y_test.columns)
            }

            # ---------- MAE evaluation per target for train and test dataset ----------
            train_mae_per_target = {
                col: float(
                    mean_absolute_error(self.Y_train[col], self.y_train_pred[:, idx])
                )
                for idx, col in enumerate(self.Y_train.columns)
            }
            test_mae_per_target = {
                col: float(
                    mean_absolute_error(self.Y_test[col], self.y_test_pred[:, idx])
                )
                for idx, col in enumerate(self.Y_test.columns)
            }

            # ---------- MSE evaluation per target for train and test dataset ----------
            train_mse_per_target = {
                col: float(
                    mean_squared_error(self.Y_train[col], self.y_train_pred[:, idx])
                )
                for idx, col in enumerate(self.Y_train.columns)
            }
            test_mse_per_target = {
                col: float(
                    mean_squared_error(self.Y_test[col], self.y_test_pred[:, idx])
                )
                for idx, col in enumerate(self.Y_test.columns)
            }

            # ---------- Root MAE evaluation per target for train and test dataset ----------
            train_rmse_per_target = {
                col: float(np.sqrt(train_mse_per_target[col]))
                for col in self.Y_train.columns
            }
            test_rmse_per_target = {
                col: float(np.sqrt(test_mse_per_target[col]))
                for col in self.Y_test.columns
            }

            return {
                "train_r2_mean": float(np.mean(list(train_r2_per_target.values()))),
                "test_r2_mean": float(np.mean(list(test_r2_per_target.values()))),
                "train_mae_mean": float(np.mean(list(train_mae_per_target.values()))),
                "test_mae_mean": float(np.mean(list(test_mae_per_target.values()))),
                "train_mse_mean": float(np.mean(list(train_mse_per_target.values()))),
                "test_mse_mean": float(np.mean(list(test_mse_per_target.values()))),
                "train_rmse_mean": float(np.mean(list(train_rmse_per_target.values()))),
                "test_rmse_mean": float(np.mean(list(test_rmse_per_target.values()))),
                "train_r2_per_target": train_r2_per_target,
                "test_r2_per_target": test_r2_per_target,
                "train_mae_per_target": train_mae_per_target,
                "test_mae_per_target": test_mae_per_target,
                "train_mse_per_target": train_mse_per_target,
                "test_mse_per_target": test_mse_per_target,
                "train_rmse_per_target": train_rmse_per_target,
                "test_rmse_per_target": test_rmse_per_target,
            }

        # ---------- Single-output regression ----------
        train_mse = float(
            mean_squared_error(self.Y_train, self.y_train_pred)
        )  # Train dataset MSE
        test_mse = float(
            mean_squared_error(self.Y_test, self.y_test_pred)
        )  # Test dataset MSE

        return {
            "train_r2": float(r2_score(self.Y_train, self.y_train_pred)),
            "test_r2": float(r2_score(self.Y_test, self.y_test_pred)),
            "train_mae": float(mean_absolute_error(self.Y_train, self.y_train_pred)),
            "test_mae": float(mean_absolute_error(self.Y_test, self.y_test_pred)),
            "train_mse": train_mse,
            "test_mse": test_mse,
            "train_rmse": float(np.sqrt(train_mse)),
            "test_rmse": float(np.sqrt(test_mse)),
        }


# =================================================
